# Generated by Django 4.2.16 on 2026-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snaps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapstory",
            name="sound_track",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="snapstory",
            name="sound_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
