# Generated by Django 4.2.16 on 2026-08-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snaps", "0003_snapgroupstreak"),
    ]

    operations = [
        migrations.AddField(
            model_name="snap",
            name="media_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="snapstory",
            name="media_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
