# Generated by Django 4.2.16 on 2026-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snaps", "0004_snap_media_url_snapstory_media_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snap",
            name="media_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="snapstory",
            name="media_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
