# Generated by Django 4.2.16 on 2026-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snaps", "0005_alter_snap_media_url_alter_snapstory_media_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="snap",
            name="reactions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="snap",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
