# Generated by Django 4.2.16 on 2026-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snaps", "0006_snap_reactions_snap_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="snap",
            name="comments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
