# Generated by Django 4.2.16 on 2026-07-19 00:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupchat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="group_voice/",
            ),
        ),
    ]
