# Generated by Django 4.2.16 on 2026-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupchat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessage",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="group_voice/"),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="audio_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmessage",
            name="message_type",
            field=models.CharField(default="text", max_length=20),
        ),
    ]
