# Generated by Django 4.2.16 on 2026-08-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupchat", "0002_alter_groupmessage_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessage",
            name="media_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
