# Generated by Django 4.2.16 on 2026-06-21 15:10

import content.auto_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupchat", "0002_groupmessage_audio_groupmessage_audio_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="image",
            field=models.FileField(
                blank=True,
                storage=content.auto_storage.AutoCloudinaryStorage(),
                upload_to="group_messages/",
            ),
        ),
    ]
