# Generated by Django 4.2.16 on 2026-06-29 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique slug for WebSocket room name",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "Private (1-on-1)"),
                            ("group", "Group Chat"),
                            ("mesh", "Mesh Room (Offline P2P)"),
                            ("broadcast", "Broadcast Channel"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("last_message", models.TextField(blank=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invite_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeshNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=64, unique=True)),
                ("public_key", models.TextField(help_text="E2E encryption public key")),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesh_node",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeshMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_node_id", models.CharField(db_index=True, max_length=64)),
                ("encrypted_payload", models.BinaryField()),
                ("ttl", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "relayed_by",
                    models.ManyToManyField(
                        blank=True, related_name="relayed_messages", to="mesh.meshnode"
                    ),
                ),
                (
                    "sender_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="mesh.meshnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatRoomMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("unread_count", models.IntegerField(default=0)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mesh.chatroom"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-room__last_message_at"],
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                related_name="chat_rooms",
                through="mesh.ChatRoomMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ChatRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, help_text="Optional intro message", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chat_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_chat_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("reaction", "Reaction"),
                            ("system", "System"),
                            ("voice", "Voice Note"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("reactions", models.JSONField(blank=True, default=dict)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="mesh.chatmessage",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mesh.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PeerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peer_node_id", models.CharField(db_index=True, max_length=64)),
                ("peer_username", models.CharField(blank=True, max_length=150)),
                ("signal_strength", models.IntegerField(default=0)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="mesh.meshnode",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_active"],
                "unique_together": {("node", "peer_node_id")},
            },
        ),
        migrations.AddIndex(
            model_name="meshnode",
            index=models.Index(
                fields=["node_id"], name="mesh_meshno_node_id_75f643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meshnode",
            index=models.Index(
                fields=["-last_seen"], name="mesh_meshno_last_se_f36da8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meshmessage",
            index=models.Index(
                fields=["recipient_node_id", "-created_at"],
                name="mesh_meshme_recipie_8a36bc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroommembership",
            unique_together={("user", "room")},
        ),
        migrations.AlterUniqueTogether(
            name="chatrequest",
            unique_together={("from_user", "to_user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "-created_at"], name="mesh_chatme_room_id_715dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "-created_at"], name="mesh_chatme_sender__9488b5_idx"
            ),
        ),
    ]
