# Generated by Django 4.2.16 on 2026-07-10 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mesh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_node_id", models.CharField(db_index=True, max_length=64)),
                (
                    "encrypted_payload",
                    models.BinaryField(
                        help_text="Encrypted with recipient's public key"
                    ),
                ),
                ("ttl", models.IntegerField(default=50, help_text="Max relay hops")),
                ("hop_count", models.IntegerField(default=0)),
                (
                    "relayed_by",
                    models.JSONField(
                        default=list, help_text="Node IDs that relayed this message"
                    ),
                ),
                ("delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_relay_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_node_id", "-created_at"],
                        name="mesh_relaym_recipie_e06f8f_idx",
                    ),
                    models.Index(
                        fields=["delivered", "-created_at"],
                        name="mesh_relaym_deliver_faaeb8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OpticalRelayNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "node_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optical_relay_node",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["node_id"], name="mesh_optica_node_id_79a421_idx"
                    ),
                    models.Index(
                        fields=["-last_seen"], name="mesh_optica_last_se_d85b7f_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-last_seen"],
                        name="mesh_optica_is_acti_929283_idx",
                    ),
                ],
            },
        ),
    ]
