# Generated by Django 4.2.16 on 2026-06-07 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mesh", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("reaction", "Reaction"),
                            ("system", "System"),
                            ("voice", "Voice Note"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("reactions", models.JSONField(blank=True, default=dict)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, help_text="Optional intro message", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique slug for WebSocket room name",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "Private (1-on-1)"),
                            ("group", "Group Chat"),
                            ("mesh", "Mesh Room (Offline P2P)"),
                            ("broadcast", "Broadcast Channel"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("last_message", models.TextField(blank=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invite_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoomMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("unread_count", models.IntegerField(default=0)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_pinned", "-room__last_message_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="peerconnection",
            options={"ordering": ["-last_active"]},
        ),
        migrations.AddField(
            model_name="meshnode",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="peerconnection",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="peerconnection",
            name="peer_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="meshmessage",
            name="relayed_by",
            field=models.ManyToManyField(
                blank=True, related_name="relayed_messages", to="mesh.meshnode"
            ),
        ),
        migrations.AlterField(
            model_name="meshnode",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meshnode",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meshnode",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meshnode",
            name="public_key",
            field=models.TextField(help_text="E2E encryption public key"),
        ),
        migrations.AlterField(
            model_name="peerconnection",
            name="peer_node_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="peerconnection",
            unique_together={("node", "peer_node_id")},
        ),
        migrations.AddIndex(
            model_name="meshnode",
            index=models.Index(
                fields=["node_id"], name="mesh_meshno_node_id_75f643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meshnode",
            index=models.Index(
                fields=["-last_seen"], name="mesh_meshno_last_se_f36da8_idx"
            ),
        ),
        migrations.AddField(
            model_name="chatroommembership",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mesh.chatroom"
            ),
        ),
        migrations.AddField(
            model_name="chatroommembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                related_name="chat_rooms",
                through="mesh.ChatRoomMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatrequest",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_chat_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatrequest",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_chat_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="mesh.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mesh.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroommembership",
            unique_together={("user", "room")},
        ),
        migrations.AlterUniqueTogether(
            name="chatrequest",
            unique_together={("from_user", "to_user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "-created_at"], name="mesh_chatme_room_id_715dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "-created_at"], name="mesh_chatme_sender__9488b5_idx"
            ),
        ),
    ]
