# Generated by Django 4.2.16 on 2026-07-13 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mesh", "0002_relaymessage_opticalrelaynode"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeshRegionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2, unique=True)),
                ("country_name", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("requires_verification", models.BooleanField(default=False)),
                ("max_range_meters", models.IntegerField(default=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mesh Region Policy",
                "verbose_name_plural": "Mesh Region Policies",
            },
        ),
        migrations.CreateModel(
            name="MeshRelayNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("messages_relayed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country_code", "-last_seen"],
                        name="mesh_meshre_country_9d76e2_idx",
                    )
                ],
            },
        ),
    ]
