# Generated by Django 4.2.16 on 2026-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="duration",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="reel",
            name="is_reported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reel",
            name="playback_speed",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="reel",
            name="sound_track",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="reel",
            name="sound_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
