# Generated by Django 4.2.16 on 2026-07-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_reel_duration_reel_is_reported_reel_playback_speed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("followers", "Followers Only")],
                default="public",
                max_length=15,
            ),
        ),
    ]
