# Generated by Django 4.2.16 on 2026-07-05 07:10

import content.auto_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_post_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(default="Original", max_length=200)),
                (
                    "audio_file",
                    models.FileField(
                        storage=content.auto_storage.AutoCloudinaryStorage(),
                        upload_to="sounds/",
                    ),
                ),
                ("duration", models.FloatField(default=0)),
                ("start_time", models.FloatField(default=0)),
                ("end_time", models.FloatField(default=0)),
                ("is_public", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_sounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
    ]
