# Generated by Django 4.2.16 on 2026-07-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_sound"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"ordering": ["-created_at"]},
        ),
    ]
