# Generated by Django 4.2.16 on 2026-08-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_story_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
