# Generated by Django 4.2.16 on 2026-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_post_media_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="reel",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
