# Generated by Django 4.2.16 on 2026-06-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_reelcommentreplylike"),
    ]

    operations = [
        migrations.AddField(
            model_name="reelcommentreply",
            name="reaction",
            field=models.CharField(default="❤️", max_length=10),
        ),
        migrations.AddField(
            model_name="reelcommentreplylike",
            name="reaction",
            field=models.CharField(default="❤️", max_length=10),
        ),
    ]
