# Generated by Django 4.2.16 on 2026-06-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_reelcommentreply_reaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reelcommentreply",
            name="reaction",
        ),
        migrations.AddField(
            model_name="reelcommentlike",
            name="reaction",
            field=models.CharField(default="❤️", max_length=10),
        ),
    ]
