# Generated by Django 4.2.16 on 2026-06-20 20:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_remove_reelcommentreply_reaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="video",
            field=models.FileField(
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="reels/",
            ),
        ),
    ]
