# Generated by Django 4.2.16 on 2026-06-20 21:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_alter_reel_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="posts/",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="media",
            field=models.FileField(
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="stories/",
            ),
        ),
    ]
