# Generated by Django 4.2.16 on 2026-06-20 21:40

import content.auto_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_alter_post_media_alter_story_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True,
                storage=content.auto_storage.AutoCloudinaryStorage(),
                upload_to="posts/",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="media",
            field=models.FileField(
                storage=content.auto_storage.AutoCloudinaryStorage(),
                upload_to="stories/",
            ),
        ),
    ]
