# Generated by Django 4.2.16 on 2026-08-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liveaudio", "0001_initial"),
    ]

    operations = []
