# Generated by Django 4.2.16 on 2026-08-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveaudio", "0002_background_and_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioroom",
            name="background_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audioroom",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
