# Generated by Django 4.2.16 on 2026-07-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacechatmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
