# Generated by Django 4.2.16 on 2026-08-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_marketplacechatmessage_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
