# Generated by Django 4.2.16 on 2026-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monetization",
            "0004_adcampaign_target_age_max_adcampaign_target_age_min_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("donation", "Donation"),
                    ("subscription", "Subscription"),
                    ("ad_reward", "Ad Reward"),
                    ("engagement_reward", "Engagement Reward"),
                    ("topup", "Top Up"),
                    ("withdrawal", "Withdrawal"),
                    ("gig_completed", "Gig Completed"),
                    ("tutoring_completed", "Tutoring Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
