# Generated by Django 4.2.16 on 2026-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0004_safwan_admin_v3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("donation", "Donation"),
                    ("subscription", "Subscription"),
                    ("ad_reward", "Ad Reward"),
                    ("engagement_reward", "Engagement Reward"),
                    ("topup", "Top Up"),
                    ("withdrawal", "Withdrawal"),
                    ("gig_completed", "Gig Completed"),
                    ("tutoring_completed", "Tutoring Completed"),
                    ("escrow_hold", "Escrow Hold"),
                    ("escrow_release", "Escrow Release"),
                    ("escrow_refund", "Escrow Refund"),
                    ("platform_fee", "Platform Fee"),
                    ("crypto_pending", "Crypto Pending"),
                    ("crypto_confirmed", "Crypto Confirmed"),
                ],
                max_length=20,
            ),
        ),
    ]
