# Generated by Django 4.2.16 on 2026-07-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gigs", "0002_gigchatmessage_is_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="gigchatmessage",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gigchatmessage",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
