# Generated by Django 4.2.16 on 2026-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gigs", "0003_gigchatmessage_file_name_gigchatmessage_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="proposal_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="gig",
            name="proposed_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("disputed", "Disputed"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
