# Generated by Django 4.2.16 on 2026-08-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gigs", "0005_gigproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
