# Generated by Django 4.2.16 on 2026-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gigs", "0006_gig_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
