# Generated by Django 4.2.16 on 2026-08-08 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gigs", "0007_gig_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_gigs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
