# Generated by Django 4.2.16 on 2026-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gigs", "0008_gig_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
