# Generated by Django 4.2.16 on 2026-06-11 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("brand_logo", models.URLField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="Specific requirements for creators"
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "Social Post"),
                            ("video", "Video Content"),
                            ("story", "Story/Reel"),
                            ("review", "Product Review"),
                            ("unboxing", "Unboxing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_audience",
                    models.IntegerField(
                        default=0, help_text="Minimum audience size required"
                    ),
                ),
                ("preferred_niche", models.CharField(blank=True, max_length=100)),
                ("deadline", models.DateTimeField()),
                ("max_creators", models.IntegerField(default=10)),
                ("applied_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SponsoredContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "Social Post"),
                            ("video", "Video Content"),
                            ("story", "Story/Reel"),
                            ("review", "Product Review"),
                            ("unboxing", "Unboxing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caption", models.TextField()),
                (
                    "media",
                    models.FileField(blank=True, null=True, upload_to="sponsored/"),
                ),
                ("media_url", models.URLField(blank=True, null=True)),
                (
                    "platform_fee_pct",
                    models.FloatField(
                        default=10.0, help_text="Platform fee percentage"
                    ),
                ),
                (
                    "creator_earnings",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed & Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("brand_feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="creatorstudio.brandcampaign",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsored_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niche",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("fashion", "Fashion"),
                            ("gaming", "Gaming"),
                            ("beauty", "Beauty"),
                            ("fitness", "Fitness"),
                            ("food", "Food & Cooking"),
                            ("travel", "Travel"),
                            ("music", "Music"),
                            ("art", "Art & Design"),
                            ("education", "Education"),
                            ("finance", "Finance"),
                            ("lifestyle", "Lifestyle"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Tell brands about yourself"
                    ),
                ),
                ("audience_size", models.IntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                (
                    "price_per_post",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
                ),
                (
                    "price_per_video",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "price_per_story",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("completed_deals", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=5.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_earned"],
            },
        ),
    ]
