# Generated by Django 4.2.16 on 2026-07-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creatorstudio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandcampaign",
            name="image",
            field=models.URLField(
                blank=True, help_text="Campaign banner image URL", null=True
            ),
        ),
    ]
