# Generated by Django 4.2.16 on 2026-07-26 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("creatorstudio", "0002_brandcampaign_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandcampaign",
            name="brand_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
