# Generated by Django 4.2.16 on 2026-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creatorstudio", "0003_brandcampaign_brand_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsoredcontent",
            name="submission_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
