# Generated by Django 4.2.16 on 2026-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="background_image",
            field=models.URLField(
                blank=True, help_text="URL for session background image", null=True
            ),
        ),
    ]
