# Generated by Django 4.2.16 on 2026-08-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0002_tutoringsession_background_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringsession',
            name='signaling',
        ),
    ]