# Generated by Django 4.2.16 on 2026-08-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0003_drop_signaling_sql"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
