# Generated by Django 4.2.16 on 2026-06-04 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0004_tutoringchatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutoringchatmessage",
            name="image",
        ),
        migrations.AlterField(
            model_name="tutoringchatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
