# Generated by Django 4.2.16 on 2026-08-21 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0005_sessionenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionenrollment",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tutoringchatmessage",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutoringchatmessage",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutoringchatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tutoring/chat/"),
        ),
        migrations.AddField(
            model_name="tutoringchatmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="certifications",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="website_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tutoringchatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
