# Generated by Django 4.2.16 on 2026-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0006_sessionenrollment_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="tutor_joined",
            field=models.BooleanField(default=False),
        ),
    ]
