# Generated by Django 4.2.16 on 2026-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0007_tutoringsession_tutor_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="topic_detail",
            field=models.TextField(blank=True, default=""),
        ),
    ]
