# Generated by Django 4.2.16 on 2026-08-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0008_tutoringsession_topic_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmaterial",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
