# Generated by Django 4.2.16 on 2026-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0009_sessionmaterial_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
