# Generated by Django 4.2.16 on 2026-08-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
