# Generated by Django 4.2.16 on 2026-08-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_create_admin_safwan"),
        ("users", "0003_make_supadmin_admin"),
    ]

    operations = []
