# Generated by Django 4.2.16 on 2026-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20260829_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="crypto_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="crypto_network",
            field=models.CharField(default="TRC20", max_length=20),
        ),
    ]
