# Generated by Django 4.2.16 on 2026-09-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_wallet_crypto_address_wallet_crypto_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="crypto_address",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="crypto_network",
        ),
    ]
