# Generated by Django 4.2.16 on 2026-06-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="freeze_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="wallet",
            name="frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_frozen",
            field=models.BooleanField(default=False),
        ),
    ]
