# Generated by Django 4.2.16 on 2026-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_wallet_freeze_reason_wallet_frozen_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="ban_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="wallet",
            name="banned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wallet",
            name="warning_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
