# Generated by Django 4.2.16 on 2026-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_wallet_ban_reason_wallet_banned_at_wallet_is_banned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
